### ISSUE TITLE
deepcopy file fails to generate if there is a missing doc.go file

### ISSUE THREAD

**Issue by LiliC** [kubernetes/code-generator#41]
While running the deepcopy file generation, there were no error msgs indicating that something fails, just the file was not generated. Took me a bit longer to figure out I forgot to create the `doc.go` file. I think it would be useful to error out if the doc.go file is not in the correct path. I ran the following command with no doc.go file and got the same output as when it was successful:

```
./generate-groups.sh deepcopy github.com/lilic/k8s-start-stop/pkg/client github.com/lilic/k8s-start-stop/pkg/apis/ "schedule:v1alpha1"

Generating deepcopy funcs
```

cc @nikhita @sttts

**Comment by sttts** [comment]
Wasn't the actual problem that the deepcopy-gen=package tag was missing in the doc.go (because there wasn't doc.go) ?

There might be valid cases when you don't want package wide generation for deepcopy. Am not really sure how a good UX would look like. Am not sure that the missing doc.go should be a fatal error, but maybe a warning?

**Comment by LiliC** [comment]
> Wasn't the actual problem that the deepcopy-gen=package tag was missing in the doc.go (because there wasn't doc.go) ?

Yes, sorry that was the actual problem.

> Am not sure that the missing doc.go should be a fatal error, but maybe a warning?

A warning would be super useful as well!

**Comment by sttts** [comment]
@LiliC do you feel like creating a PR? https://github.com/kubernetes/gengo/blob/master/examples/deepcopy-gen/generators/deepcopy.go#L145 should be a good place for such a warning.
