### ISSUE TITLE
Suggestiong add boilerplate header file to this repo

### ISSUE THREAD

**Issue by maleck13** [kubernetes/code-generator#6]
When using this repo, it still looks for the boilerplate header which is located in the kubernetes repo
https://github.com/kubernetes/kubernetes/blob/master/hack/boilerplate/boilerplate.go.txt

Wondering would it be better to have the boilerplate as part of this repo?

**Comment by ash2k** [comment]
Similar issue https://github.com/kubernetes/kubernetes/issues/50975

**Comment by kopiczko** [comment]
I just ran into that issue. We run `generate-groups.sh` from vendor directory to make it reproducible. When `k8s.io/kubernetes/hack/boilerplate` isn't in the `$GOPATH` `generate-groups.sh` complains:

```
Generating deepcopy funcs
ERROR: logging before flag.Parse: F1125 16:42:32.929374   57968 deepcopy.go:126] Failed loading boilerplate: open /Users/pawel/go/src/k8s.io/kubernetes/hack/boilerplate/boilerplate.go.txt: no such file or directory
goroutine 1 [running]:
github.com/giantswarm/apiextensions/vendor/github.com/golang/glog.stacks(0xc42000e000, 0xc4276d6d80, 0xb5, 0x105)
        /Users/pawel/go/src/github.com/giantswarm/apiextensions/vendor/github.com/golang/glog/glog.go:769 +0xcf
github.com/giantswarm/apiextensions/vendor/github.com/golang/glog.(*loggingT).output(0x145c3a0, 0xc400000003, 0xc427774370, 0x1438300, 0xb, 0x7e, 0x0)
        /Users/pawel/go/src/github.com/giantswarm/apiextensions/vendor/github.com/golang/glog/glog.go:720 +0x345
github.com/giantswarm/apiextensions/vendor/github.com/golang/glog.(*loggingT).printf(0x145c3a0, 0x3, 0x12eb243, 0x1e, 0xc4259d3cf0, 0x1, 0x1)
        /Users/pawel/go/src/github.com/giantswarm/apiextensions/vendor/github.com/golang/glog/glog.go:655 +0x14c
github.com/giantswarm/apiextensions/vendor/github.com/golang/glog.Fatalf(0x12eb243, 0x1e, 0xc4259d3cf0, 0x1, 0x1)
        /Users/pawel/go/src/github.com/giantswarm/apiextensions/vendor/github.com/golang/glog/glog.go:1148 +0x67
github.com/giantswarm/apiextensions/vendor/k8s.io/gengo/examples/deepcopy-gen/generators.Packages(0xc4276f5f80, 0xc4200cc1b0, 0x12e3ecf, 0x6, 0xc4276f5f80)
        /Users/pawel/go/src/github.com/giantswarm/apiextensions/vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go:126 +0xd2
github.com/giantswarm/apiextensions/vendor/k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc4200cc1b0, 0xc420082c30, 0x12e3ecf, 0x6, 0x12f26c8, 0x0, 0x0)
        /Users/pawel/go/src/github.com/giantswarm/apiextensions/vendor/k8s.io/gengo/args/args.go:176 +0x1d4
main.main()
        /Users/pawel/go/src/github.com/giantswarm/apiextensions/vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:74 +0x1c0
```

**Comment by prateeknayak** [comment]
Ran into the same issue with code-generator version `1.8.6` ... it seems as if `client-gen` does not like the `--go-header-file` flag where as the `deepcopy-gen` will default to `<kuberepo>/hack/boilerplate/boilerplate.go.txt` if `--go-header-file` not provided.

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/kubernetes/pull/57656.

/cc @sttts

**Comment by sslavic** [comment]
Ran into same issue as @prateeknayak. It used to be possible to use `generate-groups.sh all` and pass `--go-header-file` flag. Now, while using code-generator release-1.8, `deepcopy-gen` passes but `client-gen` fails as it doesn't need/accept `--go-header-file` flag.

Running `generate-groups.sh all` without `--go-header-file` flag makes `deepcopy-gen` fail, since it's looking for default boilerplate file (`$GOPATH/src/k8s.io/kubernetes/hack/boilerplate/boilerplate.go.txt`) which doesn't exist.

I guess workaround is to use/invoke individual generators separately instead of using `all`.

Should there be a separate ticket or will this one address either fix that `all` works again, or removal of support for `all` from `generate-groups.sh`? Maybe `generate-internal-groups.sh` has same issue.

**Comment by sslavic** [comment]
Tried working around the issue by running generators independently:
- only `deepcopy` passes with `--go-header-file` flag set
- `client` generator doesn't ignore `--go-header-file` being set, it fails when the flag is set and outputs usage instructions, and it also fails when it's omitted because it cannot load the default boilerplate file
- `lister` and `informer` generators both seem to ignore `--go-header-file` being set, but fail since they cannot load the default boilerplate file, and same happens when the flag is not set

**Comment by sslavic** [comment]
Problem goes away when using release-1.9 (over release-1.8) - all 4 generators accept `--go-header-file` flag.
